---
# tasks file for arillso.ntp

- name: add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/defaults.yml"
  tags:
    - configuration
    - packages

- name: install ntp
  become: true
  package:
    name: "{{ ntp_package_name }}"
  notify: enabled ntp
  tags:
    - packages

- name: copy config
  become: true
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - enabled ntp
    - restart ntp
  tags:
    - configuration
