---
- name: add the OS specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: install ntp on RedHat
  yum: name=ntp state=latest
  when: ansible_os_family == 'RedHat'

- name: install ntp on Debian
  apt: name=ntp state=latest
  when: ansible_os_family == 'Debian'

- name: copy config
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
  - restart ntp

- name: enabled ntp service
  service: name={{ ntp_service_name }} enabled=yes
